name: Expresiones
on:
    workflow_dispatch
jobs:
    build:
        strategy: 
            fail-fast: false
            matrix:
                so: [windows-latest, ubuntu-latest]
        name: matriz uni-dimensional
        runs-on: ${{matrix.so}}
        steps:
            - name: paso solo para Windows
              if: ${{matrix.so == 'windows-latest'}}
              run: |
                echo "Solo Windows"
            - name: paso para todos
              run: |
                echo "Para todos"