name: hola mundo

# on:
#   push:
#     branches:
#       - main

on:
  schedule:
    - cron: '*/30 * * * *' # cada 5 minutos
  push:
    branches:
      - main

jobs: 
  saludar:
    runs-on: ubuntu-latest
    steps: 
      - name: muestra mensaje 
        run: echo "hola mundo, soy Villaran"
