name: hola mundo

# on:
#   push:
#     branches:
#       - main

on:
  workflow_dispatch:
  # schedule:
  #   - cron: '*/30 * * * *' # cada 30 minutos
  push:
    branches:
      - main
    paths:
      - 'codigo/**'
      - './github/workflows/holamundo.yml'
      # - dev
  pull_request: 
    branches:
      - main

jobs: 
  saludar:
    runs-on: ubuntu-latest
    steps: 
      - name: muestra mensaje 
        run: echo "hola mundo, soy Villaran"
        
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: List repo files
        run: |
          echo "El repo ${{github.repository}} contiene los siguientes archivos: "
          tree
