name: Issues ejemplo

on: 
  issues: 
    types: # Tambien se puede usar [opened]
      - opened 
jobs: 
  procesa-issue:
    runs-on: ubuntu-latest
    steps: 
      - name: Muestra el titulo del Issue
        run: echo "El titulo del issue es ${{github.event.issue.title}}"
