name: variables

on: 
    workflow_dispatch

env:
    variable_global: VARIABLE GLOBAL
    name1: MARIA

jobs: 
    job1:
        runs-on: ubuntu-latest
        env:
            variable_job: VARIABLE JOB
            name2: ALOY
        steps:
            - name: Step 1 del Job 1
              run:  |
                echo: "El valor de la variable global es $variable_global
                echo: "Otra forma es ${{ env.variable_global }}"
                echo: $name1 y $name2 <3
            